---
title: ' '
subtitle: Kevin Chen's Data Science Portfolio
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Abstract

This is the computation of datas that is going to be used for building a dataset showing trends and correlation about video games between their sales, rating, when they were sold and etc. The final hope was to show what major factor effect the overall value of the video game.

### 1. Discovery and Data Preparation

This is the first part of the portfolio with the intial dataset. 
[The first part of the dataset](Portfolio1ver2.html)

### 2. Model Planning and Building
In this second part I had scrap information from website pertaining platform sale in hope to help paint a bigger picture of help giving more depth to the original data and build some sort of model.
Change has been made to the first as well.
[The second part of the dataset](Portfolio2actual.html)

### 3. Results and Operationalization
This is the final part of the portfolio contenting final thought and possible conclusion for the video game sales portfolio. 
[The third part of the dataset](Portfolio3.html)

